name: Semantic release

on:
  schedule:
    - cron: "0 18 * * 5" # At 18:00 on Friday.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0

      - name: Configuration
        uses: DamianReeves/write-file-action@6929a9a6d1807689191dcc8bbe62b54d70a32b42 # v1.3
        with:
          path: .releaserc.yml
          contents: |
            branches:
              - "main"
            plugins:
              - - "@semantic-release/commit-analyzer"
                - releaseRules:
                    - type: chore
                      scope: deps
                      release: patch

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@9cc899c47e6841430bbaedb43de1560a568dfd16 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
